{
 "title": "Istio Service RED Method",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(destination_service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rate (average request per second) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps", "label": "requests per second" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_workload) (rate(istio_requests_total{reporter=\"source\",destination_service=\"$service\"}[5m]))",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Errors (average errors per second) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps", "label": "errors per second" }
   ],
   "targets": [
    {
     "expr": "sum by (destination_workload) (rate(istio_requests_total{reporter=\"source\",destination_service=\"$service\",response_code=~\"5.*\"}[5m]))",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le) (rate(istio_request_duration_seconds_bucket{destination_service=\"details.bookinfo.svc.cluster.local\"}[5m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}