{
 "title": "Istio Service USE Method",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(destination_service)"
   },
   {
    "name": "dstns",
    "label": "Destination Workloand Namespace",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=\"$service\"}) by (destination_workload_namespace))"
   },
   {
    "name": "dstn",
    "label": "Destination Workload Name",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=\"$service\", destination_workload_namespace=\"$dstns\"}) by (destination_workload))"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~\"$dstn.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "sum by (pod,namespace) (rate(container_cpu_cfs_throttled_seconds_total{container!=\"\",pod=~\"$dstn.*\"}[5m]))\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Error",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "content": "\n\n<center> <h1> N/A </h1>  </center>\n\n\n"
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "gbytes", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"\",pod=~\"$dstn.*\"}/(2^30)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{container!=\"\",pod=~\"$dstn.*\"}/ on (pod,container) label_join(kube_pod_container_resource_limits_memory_bytes{pod=~\"$dstn.*\"},\"container_name\", \"\", \"container\")) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    {
     "format": "short",
     "label": "Error Average Count in the last 5 minutes"
    }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"$dstn.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "mbytes", "label": "Rec + Trans MiB" }
   ],
   "targets": [
    {
     "expr": " (sum by (pod)(rate(container_network_transmit_bytes_total{pod=~\"$dstn.*\"}[5m])) + sum by (pod) (rate(container_network_receive_bytes_total{pod=~\"$dstn.*\"}[5m]))) / (2^24)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Saturation",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "content": "\n\n<center> <h1> N/A </h1>  </center>\n\n\n"
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    {
     "format": "short",
     "label": "Average Error Rate in the last 5 minutes"
    }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_errors_total{pod=~\"$dstn.*\"}[5m])) + sum by (pod) (rate(container_network_transmit_errors_total{pod=~\"$dstn.*\"}[5m])) + sum by (pod) (rate(container_network_receive_packets_dropped_total{pod=~\"$dstn.*\"}[5m])) + sum by (pod) (rate(container_network_transmit_packets_dropped_total{pod=~\"$dstn.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "gbytes", "label": "File System Usage" }
   ],
   "targets": [
    {
     "expr": "pod:container_fs_usage_bytes:sum{pod=~\"$dstn.*\"} / (2^30)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Saturation",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "content": "\n\n<center> <h1> N/A </h1>  </center>\n\n\n"
  },
  {
   "title": "Disk Saturation",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "content": "\n\n<center> <h1> N/A </h1>  </center>\n\n\n"
  }
 ]
}