{{ if .Values.usePostgresql }}
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-{{ include "backstage.fullname" . }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: pgadmin
{{ end }}    
