apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: approved-namespaces
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/raf-backstage-demo/approved-namespaces.git
    targetRevision: HEAD
    path: "."
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - Validate=false
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true      
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  ignoreDifferences:
  - group: backstage.io
    kind: System
    jsonPointers:
    - /metadata/description     