apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: patch-operator-inject
  labels:
    {{- include "openshift-config.labels" . | nindent 4 }}  
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: patch-operator-controller-manager-service
      namespace: patch-operator
      path: /inject
    caBundle: Cg==
  failurePolicy: Fail
  name: patch-operator-inject.redhatcop.redhat.io
  rules:
  - apiGroups:
    - "dbaas.redhat.com"
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - dbaasconnections
  sideEffects: None